@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.teamlapen.vampirism.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;